// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223184221_TiposInventario")]
    partial class TiposInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("API.Entities.Inventario", b =>
                {
                    b.Property<string>("NoParte")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IDUnidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("NoParte");

                    b.HasIndex("IDUnidad");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("API.Entities.LogInventario", b =>
                {
                    b.Property<int>("IDLogInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDTipoMovimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoParte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDLogInventario");

                    b.HasIndex("IDSucursal");

                    b.HasIndex("IDTipoMovimiento");

                    b.HasIndex("IDUsuario");

                    b.HasIndex("NoParte");

                    b.ToTable("LogInventario");
                });

            modelBuilder.Entity("API.Entities.Modulo", b =>
                {
                    b.Property<int>("IDModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDModuloCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDModulo");

                    b.HasIndex("IDModuloCategoria");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("API.Entities.ModulosAcceso", b =>
                {
                    b.Property<int>("IDModuloAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDModulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDNivelAcceso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDPerfilPuesto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDModuloAcceso");

                    b.HasIndex("IDModulo");

                    b.HasIndex("IDNivelAcceso");

                    b.HasIndex("IDPerfilPuesto");

                    b.ToTable("ModulosAcceso");
                });

            modelBuilder.Entity("API.Entities.ModulosCategoria", b =>
                {
                    b.Property<int>("IDModuloCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDModuloCategoria");

                    b.ToTable("ModulosCategorias");
                });

            modelBuilder.Entity("API.Entities.NivelesAcceso", b =>
                {
                    b.Property<int>("NivelAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NivelAcceso");

                    b.ToTable("NivelesAcceso");
                });

            modelBuilder.Entity("API.Entities.PerfilPuesto", b =>
                {
                    b.Property<int>("IDPerfilPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDPerfilPuesto");

                    b.ToTable("PerfilesPuesto");
                });

            modelBuilder.Entity("API.Entities.Sucursal", b =>
                {
                    b.Property<int>("IDSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDSucursal");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("API.Entities.SucursalesInventario", b =>
                {
                    b.Property<int>("IDSucursalInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoParte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UmbralExistencia")
                        .HasColumnType("TEXT");

                    b.HasKey("IDSucursalInventario");

                    b.HasIndex("IDSucursal");

                    b.HasIndex("NoParte");

                    b.ToTable("SucursalesInventario");
                });

            modelBuilder.Entity("API.Entities.TiposMovimientosInventario", b =>
                {
                    b.Property<int>("IDTipoMovimientoInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EntradaSalida")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDTipoMovimientoInventario");

                    b.ToTable("TiposMovimientosInventario");
                });

            modelBuilder.Entity("API.Entities.Unidad", b =>
                {
                    b.Property<int>("IDUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abreviacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUnidad");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("API.Entities.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ContraseniaHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ContraseniaSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IDPerfilPuesto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUsuario");

                    b.HasIndex("IDPerfilPuesto");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API.Entities.UsuarioSucursal", b =>
                {
                    b.Property<int>("IDSucursalUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDSucursalUsuario");

                    b.HasIndex("IDSucursal");

                    b.HasIndex("IDUsuario");

                    b.ToTable("UsuariosSucursales");
                });

            modelBuilder.Entity("API.Entities.Inventario", b =>
                {
                    b.HasOne("API.Entities.Unidad", "Unidad")
                        .WithMany("Productos")
                        .HasForeignKey("IDUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("API.Entities.LogInventario", b =>
                {
                    b.HasOne("API.Entities.Sucursal", "Sucursal")
                        .WithMany("LogInventario")
                        .HasForeignKey("IDSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.TiposMovimientosInventario", "TipoMovimiento")
                        .WithMany("LogInventario")
                        .HasForeignKey("IDTipoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Usuario", "QuienRealiza")
                        .WithMany("LogInventario")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Inventario", "Producto")
                        .WithMany("LogInventario")
                        .HasForeignKey("NoParte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("QuienRealiza");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("API.Entities.Modulo", b =>
                {
                    b.HasOne("API.Entities.ModulosCategoria", "ModuloCategoria")
                        .WithMany("Modulos")
                        .HasForeignKey("IDModuloCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuloCategoria");
                });

            modelBuilder.Entity("API.Entities.ModulosAcceso", b =>
                {
                    b.HasOne("API.Entities.Modulo", "Modulo")
                        .WithMany("ModulosAcceso")
                        .HasForeignKey("IDModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.NivelesAcceso", "NivelAcceso")
                        .WithMany("ModulosAcceso")
                        .HasForeignKey("IDNivelAcceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.PerfilPuesto", "PerfilPuesto")
                        .WithMany("ModulosAcceso")
                        .HasForeignKey("IDPerfilPuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("NivelAcceso");

                    b.Navigation("PerfilPuesto");
                });

            modelBuilder.Entity("API.Entities.SucursalesInventario", b =>
                {
                    b.HasOne("API.Entities.Sucursal", "Sucursal")
                        .WithMany("SucursalesInventario")
                        .HasForeignKey("IDSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Inventario", "Producto")
                        .WithMany("SucursalesInventario")
                        .HasForeignKey("NoParte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("API.Entities.Usuario", b =>
                {
                    b.HasOne("API.Entities.PerfilPuesto", "PerfilPuesto")
                        .WithMany("Usuarios")
                        .HasForeignKey("IDPerfilPuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPuesto");
                });

            modelBuilder.Entity("API.Entities.UsuarioSucursal", b =>
                {
                    b.HasOne("API.Entities.Sucursal", "Sucursal")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("IDSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.Entities.Inventario", b =>
                {
                    b.Navigation("LogInventario");

                    b.Navigation("SucursalesInventario");
                });

            modelBuilder.Entity("API.Entities.Modulo", b =>
                {
                    b.Navigation("ModulosAcceso");
                });

            modelBuilder.Entity("API.Entities.ModulosCategoria", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("API.Entities.NivelesAcceso", b =>
                {
                    b.Navigation("ModulosAcceso");
                });

            modelBuilder.Entity("API.Entities.PerfilPuesto", b =>
                {
                    b.Navigation("ModulosAcceso");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API.Entities.Sucursal", b =>
                {
                    b.Navigation("LogInventario");

                    b.Navigation("SucursalesInventario");

                    b.Navigation("UsuarioSucursales");
                });

            modelBuilder.Entity("API.Entities.TiposMovimientosInventario", b =>
                {
                    b.Navigation("LogInventario");
                });

            modelBuilder.Entity("API.Entities.Unidad", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("API.Entities.Usuario", b =>
                {
                    b.Navigation("LogInventario");

                    b.Navigation("UsuarioSucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
