// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112215222_ModulosYPerfilesPuesto")]
    partial class ModulosYPerfilesPuesto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("API.Entities.PerfilPuesto", b =>
                {
                    b.Property<int>("IDPerfilPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDPerfilPuesto");

                    b.ToTable("PerfilPuesto");
                });

            modelBuilder.Entity("API.Entities.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ContraseniaHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ContraseniaSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerfilPuestoIDPerfilPuesto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDUsuario");

                    b.HasIndex("PerfilPuestoIDPerfilPuesto");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API.Entities.Usuario", b =>
                {
                    b.HasOne("API.Entities.PerfilPuesto", "PerfilPuesto")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilPuestoIDPerfilPuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPuesto");
                });

            modelBuilder.Entity("API.Entities.PerfilPuesto", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
