// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112215535_ModulosAccesoCorrecto")]
    partial class ModulosAccesoCorrecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("API.Entities.Modulos", b =>
                {
                    b.Property<int>("IDModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuloCategoriaIDModuloCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDModulo");

                    b.HasIndex("ModuloCategoriaIDModuloCategoria");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("API.Entities.ModulosAcceso", b =>
                {
                    b.Property<int>("IDModuloAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuloIDModulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelAcceso1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerfilPuestoIDPerfilPuesto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDModuloAcceso");

                    b.HasIndex("ModuloIDModulo");

                    b.HasIndex("NivelAcceso1");

                    b.HasIndex("PerfilPuestoIDPerfilPuesto");

                    b.ToTable("ModulosAcceso");
                });

            modelBuilder.Entity("API.Entities.ModulosCategorias", b =>
                {
                    b.Property<int>("IDModuloCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDModuloCategoria");

                    b.ToTable("ModulosCategorias");
                });

            modelBuilder.Entity("API.Entities.NivelesAcceso", b =>
                {
                    b.Property<int>("NivelAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NivelAcceso");

                    b.ToTable("NivelesAcceso");
                });

            modelBuilder.Entity("API.Entities.PerfilPuesto", b =>
                {
                    b.Property<int>("IDPerfilPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDPerfilPuesto");

                    b.ToTable("PerfilPuesto");
                });

            modelBuilder.Entity("API.Entities.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ContraseniaHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ContraseniaSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerfilPuestoIDPerfilPuesto")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDUsuario");

                    b.HasIndex("PerfilPuestoIDPerfilPuesto");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API.Entities.Modulos", b =>
                {
                    b.HasOne("API.Entities.ModulosCategorias", "ModuloCategoria")
                        .WithMany("Modulos")
                        .HasForeignKey("ModuloCategoriaIDModuloCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuloCategoria");
                });

            modelBuilder.Entity("API.Entities.ModulosAcceso", b =>
                {
                    b.HasOne("API.Entities.Modulos", "Modulo")
                        .WithMany("ModulosAcceso")
                        .HasForeignKey("ModuloIDModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.NivelesAcceso", "NivelAcceso")
                        .WithMany("ModulosAcceso")
                        .HasForeignKey("NivelAcceso1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.PerfilPuesto", "PerfilPuesto")
                        .WithMany("ModulosAcceso")
                        .HasForeignKey("PerfilPuestoIDPerfilPuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("NivelAcceso");

                    b.Navigation("PerfilPuesto");
                });

            modelBuilder.Entity("API.Entities.Usuario", b =>
                {
                    b.HasOne("API.Entities.PerfilPuesto", "PerfilPuesto")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilPuestoIDPerfilPuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPuesto");
                });

            modelBuilder.Entity("API.Entities.Modulos", b =>
                {
                    b.Navigation("ModulosAcceso");
                });

            modelBuilder.Entity("API.Entities.ModulosCategorias", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("API.Entities.NivelesAcceso", b =>
                {
                    b.Navigation("ModulosAcceso");
                });

            modelBuilder.Entity("API.Entities.PerfilPuesto", b =>
                {
                    b.Navigation("ModulosAcceso");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
